from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT


class DocumentGenerator:

    def generate_investigation_report(self, analysis: dict):

        document = Document()

        # -----------------------------
        # TITLE
        # -----------------------------
        title = document.add_heading("VIDURA", level=0)
        title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

        subtitle = document.add_heading(
            "AI Generated Investigation Report",
            level=1
        )
        subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

        document.add_paragraph(
            f"Generated on: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}"
        )

        document.add_heading("Case Summary", level=2)
        document.add_paragraph(
            analysis["case"]["summary"]
        )

        document.add_heading("Victim Information", level=2)

        document.add_paragraph(
            f"Name : {analysis['victim']['name']}"
        )

        document.add_paragraph(
            f"Phone : {analysis['victim']['phone']}"
        )

        document.add_paragraph(
            f"Address : {analysis['victim']['address']}"
        )

        document.add_heading("Accused Information", level=2)

        document.add_paragraph(
            f"Name : {analysis['accused']['name']}"
        )

        document.add_paragraph(
            f"Status : {analysis['accused']['status']}"
        )

        document.add_heading("Legal Analysis", level=2)

        document.add_paragraph(
            f"Reasoning : {analysis['legal_analysis']['reasoning']}"
        )

        document.add_paragraph(
            "Recommended BNS Sections:"
        )

        for sec in analysis["legal_analysis"]["recommended_bns"]:
            document.add_paragraph(
                sec,
                style="List Bullet"
            )

        document.add_heading("Evidence Required", level=2)

        for item in analysis["evidence_required"]:
            document.add_paragraph(
                item,
                style="List Bullet"
            )

        document.add_heading("Missing Information", level=2)

        for item in analysis["missing_information"]:
            document.add_paragraph(
                item,
                style="List Bullet"
            )

        document.add_heading("Next Best Actions", level=2)

        for item in analysis["next_best_actions"]:
            document.add_paragraph(
                item,
                style="List Number"
            )

        document.add_heading("Investigation Report", level=2)

        report = analysis["investigation_report"]

        document.add_heading("Incident Summary", level=3)
        document.add_paragraph(
            report["incident_summary"]
        )

        document.add_heading("Preliminary Findings", level=3)
        document.add_paragraph(
            report["preliminary_findings"]
        )

        document.add_heading("Risk Assessment", level=3)
        document.add_paragraph(
            report["risk_assessment"]
        )

        document.add_heading("Recommended Actions", level=3)
        document.add_paragraph(
            report["recommended_actions"]
        )

        document.add_page_break()

        document.add_heading(
            "Generated by VIDURA AI",
            level=2
        )

        output_dir = Path("app/generated")
        output_dir.mkdir(
            parents=True,
            exist_ok=True
        )

        file_path = output_dir / "investigation_report.docx"

        document.save(file_path)

        return str(file_path)


document_generator = DocumentGenerator()
LAST_ANALYSIS = None